[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ccxt>=4.5.33",
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "pandas-ta",
    "ta-lib>=0.6.8",
]
