[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11,<3.13"
dependencies = [
    "ccxt>=4.5.33",
    "numpy>=1.24,<2.3",
    "pandas>=2.3.3",
    "ta-lib>=0.6.8",
    "tenacity>=9.1.2",
]
